source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-archives'
gem 'jekyll-paginate-v2'
gem 'nokogiri', '>= 1.12'
gem 'tzinfo'
gem 'yaml'
gem 'fileutils'
gem 'fastimage'